name: Release CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Which Windows version to build (v6 or v7)'
        required: true
        default: 'v7'

jobs:
  build-windows:
    name: Build Windows GUI (${ { github.event.inputs.version } })
    runs-on: windows-latest
    env:
      CONFIGURATION: Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine solution file
        id: vars
        run: |
          if [[ "${{ github.event.inputs.version }}" == "v6" ]]; then
            echo "::set-output name=solution::craxsrat_v6.sln"
            echo "::set-output name=folder::v6"
            echo "::set-output name=zip::craxsrat-v6.zip"
          else
            echo "::set-output name=solution::craxsrat_v7.sln"
            echo "::set-output name=folder::v7"
            echo "::set-output name=zip::craxsrat-v7.zip"
          fi
        shell: bash

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore ${{ steps.vars.outputs.solution }}

      - name: Build solution
        run: dotnet build ${{ steps.vars.outputs.solution }} --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Publish app
        run: |
          dotnet publish ${{ steps.vars.outputs.solution }} \
            --configuration ${{ env.CONFIGURATION }} \
            --output publish/${{ steps.vars.outputs.folder }} \
            --no-build

      - name: Zip build
        run: |
          Compress-Archive -Path publish/${{ steps.vars.outputs.folder }}/* -DestinationPath ${{ steps.vars.outputs.zip }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.version }}
          path: ${{ steps.vars.outputs.zip }}
